apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: rest-api
          image: 871988193069.dkr.ecr.us-east-1.amazonaws.com/rest-api:v1
          ports:
            - containerPort: 8080